### ISSUE TITLE
Open support (FAQ) page for doom user

### ISSUE THREAD

**Issue by takaxp** [takaxp/moom#25]

**Comment by nomm-dot** [comment]
Unable to install this package in doom via packages.el, `function definition is void`.

packages.el:
```
(package! moom)
```
error:
```
  x There was an unexpected runtime error
    Message: Symbol's function definition is void
    Details: (transient-prefix)
    Backtrace:
      (transient-prefix :command 'moom-transient-dispatch :transient-suffix 'moom-transient--do-stay)
      (put 'moom-transient-dispatch 'transient--prefix (transient-prefix :command 'moom-transient-dispatch :transient-suffix 'moom-...
      (eval-buffer #<buffer  *load*-135126> nil "/Users/noahmihalik/.emacs.d/.local/straight/build-29.1/moom/moom-autoloads.el" nil t)
      (load-with-code-conversion "/Users/noahmihalik/.emacs.d/.local/straight/build-29.1/moom/moom-autoloads.el" "/Users/noahmihali...
      (load "/Users/noahmihalik/.emacs.d/.local/straight/build-29.1/moom/moom-autoloads.el" nil nomessage)
      (progn (load autoloads-file nil 'nomessage))
      (if (file-exists-p autoloads-file) (progn (load autoloads-file nil 'nomessage)))
      (let ((autoloads-file (straight--autoloads-file package))) (if (file-exists-p autoloads-file) (progn (load autoloads-file nil...
      (straight--load-package-autoloads "moom")
      (let ((name (symbol-name package))) (add-to-list 'load-path (directory-file-name (straight--build-dir name))) (straight--load...
      (let ((package (car tail))) (straight-register-package package) (let ((name (symbol-name package))) (add-to-list 'load-path (...
      (while tail (let ((package (car tail))) (straight-register-package package) (let ((name (symbol-name package))) (add-to-list ...
GNU Emacs     v29.1            nil
Doom core     v3.0.0-pre       HEAD -> master 8846d1518 2025-03-04 14:13:38 -0500
Doom modules  v25.03.0-pre     HEAD -> master 8846d1518 2025-03-04 14:13:38 -0500
    ! Wrote extended backtrace to ~/.emacs.d/.local/state/logs/cli.doom.250324132055.33745.error
* 2.658194:*:cli:run:Finished (GCs: 1, elapsed: 0.066296s)
✓ Finished in 2.65823s
```

**Comment by takaxp** [comment]
Please try install https://github.com/magit/transient. But I'm not sure why the error is happen because `moom-transient.el` depends on the transient but `moom.el` doesn't so.

Or just installing `moom-transient.el` may resolve this issue.

**Comment by nomm-dot** [comment]
Looks like transient is included with doom by default.

**Comment by nomm-dot** [comment]
Looks like transient is already included in doom by default. I believe the following I declared in my packages.el would be correct to include moom-transient.el in the installation. Let me know if this is incorrect though. I still get the same error described above when attempting a `doom sync`

```
(package! moom
  :recipe (:host github
           :repo "https://github.com/takaxp/moom"
           :files (:defaults "moom-transient.el")))
```

**Comment by takaxp** [comment]
Thank you for the test with a specific recipe for installing moom.el.

For now, I cannot even setup Doom Emacs for my macOS due to some errors, so it is hard to reproduce the error on installing moom.el. To distinguish the cause of the error, I made an alternative repository that does not contain moom-transient.el at https://github.com/takaxp/moom_pure1

Could you try to install that using another recipe for Doom something like:

```
(package! moom
  :recipe (:host github
           :repo "https://github.com/takaxp/moom_pure1"))
```

**Comment by takaxp** [comment]
Finally the issue was reproduced on my side with Emacs 28.1+Doom release(modules): 22.08.0-dev.

The issue comes from an issue regarding the transient implementation and it has been resolved in [Emacs 30.1](https://github.com/emacsmirror/emacs/commit/167d9b9040333a5bff64325423750243c60edfa1) by modification of `loaddefs-gen.el`. This means that the solution by the modification is not applied to the earlier version like 29.4. At this moment not many people use the latest Emacs. So I decided to take [another way](https://github.com/magit/transient/issues/280#issuecomment-2019214088) to fix the issue on installing `moom` to Doom.

Changes to fix the issue is already [reflected](https://github.com/takaxp/moom/commit/d4eca80eac08f1bf5148c462518d55888df15a11#diff-8e4af0bf998f1ecab818569104b177a34b6749cf3e2e7a1bbc5572a93df0c235) to the latest `moom` package. So please update the package.

Note: Updating the `moom` has been done with the following steps:
1. comment out the config for `moom` in packages.el
2. run `doom sync -p` (or with `--gc`) to remove `moom` from package directory of straight package manager
3. remove the comment out for `moom` in packages.el
4. run `doom sync`

I'm very happy if you could try the above solution and the issue will be resolved on your side.

**Comment by nomm-dot** [comment]
So, I've commented out moom, but `-p` is not a CLI option for me. Are you maybe referring to the following option?
```
  emacs:
    gc            Deletes orphaned packages & repos, and compacts them.
```
I've also tried deleting the `/moom` dir from `~/.emacs.d/.local/straight/repos` and `~/.emacs.d/.local/straight/build-29.1` then tried a `doom sync` and a `doom upgrade`, but was still receiving the same error.

EDIT: It was a syntax error on my part after the fix. It's installed correctly now with no errors. Thanks very much for the super fast and well explained help. I really appreciate a doom specific help section since we're in a pretty strange situation among the emacs community.

**Comment by takaxp** [comment]
Yes, at least DOOM release(modules): 25.04.0-dev has an option to purge a package with `--gc` not `-p`.

And I've also confirmed that there is no error on installing `moom` in combination of Emacs 29.1(with nativecomp) and DOOM release(modules): 25.04.0-dev.

Thank you for the report and tests. I'm very comfortable since the issue is resolved.
